# Generated by Django 4.2.7 on 2023-12-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('audio', models.FileField(blank=True, upload_to='sentence_audio/')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.language')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('phonetic_spelling', models.CharField(blank=True, max_length=50)),
                ('plural', models.CharField(blank=True, max_length=50)),
                ('second_plural', models.CharField(blank=True, max_length=50)),
                ('audio', models.FileField(blank=True, upload_to='word_audio/')),
                ('descriptors', models.ManyToManyField(to='entries.descriptor')),
                ('example_sentences', models.ManyToManyField(to='entries.sentence')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.language')),
                ('translations', models.ManyToManyField(to='entries.word')),
            ],
        ),
    ]
