# Generated by Django 4.2.7 on 2023-12-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='translations',
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
                ('example_sentences', models.ManyToManyField(to='entries.sentence')),
                ('from_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.word')),
                ('to_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.language')),
            ],
        ),
    ]
