# Generated by Django 4.2.7 on 2023-12-23 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_remove_word_translations_alter_word_word_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='example_sentences',
        ),
        migrations.RemoveField(
            model_name='word',
            name='example_sentences',
        ),
        migrations.AddField(
            model_name='sentence',
            name='translated_sentence',
            field=models.ManyToManyField(to='entries.sentence'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='translation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entries.translation'),
            preserve_default=False,
        ),
    ]
