# Generated by Django 4.2.7 on 2023-12-23 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_remove_translation_example_sentences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='translation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entries.translation'),
        ),
    ]
