# Generated by Django 4.2.7 on 2023-12-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_sentence_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptor',
            name='abbreviation',
            field=models.CharField(max_length=50),
        ),
    ]
