# Generated by Django 4.2.7 on 2025-09-06 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_descriptor_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.word')),
            ],
            options={
                'verbose_name': 'Daily Word',
                'verbose_name_plural': 'Daily Words',
                'ordering': ['-featured_date'],
            },
        ),
    ]
